### ISSUE TITLE
wow cool

### ISSUE THREAD

**Issue by zpzxgcr** [aluisiora/zabbix-typescript-client#1]
nice project

**Comment by zpzxgcr** [comment]
Excuse me, will the project be maintained all the time?

**Comment by aluisiora** [comment]
I tried to make it simple so it doesn't need too much maintenance. I don't intend to take it down if it's what you mean.

I used it in some internal projects in my company, but not currently though.
We're planning to do some real crazy stuff with zabbix in the near future, so yeah, I might maintain it for quite sometime.

**Comment by zpzxgcr** [comment]
I also plan to use it in some internal projects of the company,

**Comment by aluisiora** [comment]
Closing since this is not an issue.
